n = input('Digite algo:')
print(type(n))
print('É um numero?', n.isnumeric())
print('É um Alphanumerico?', n.isalnum())
print('É decimal?', n.isdecimal())
print('esta em lestras minusculas?', n.islower())
print('Beleza, voa!')
